name: "CodeQL"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  run-codeql-linux:
    name: Run CodeQL on Macos
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: swift

    - name: Build
      run: swift build
      
    #generic/platform=iOS is sufficient for just building, - but need to specify concrete destination for tests
    - name: Build 
      run: xcodebuild build -scheme SomeApp -destination 'platform=iOS' #or any other name from the list of sim devices

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
